#!/bin/sh

interface=lan

enabled="$(uci get fakemesh.default.enabled)"
role="$(uci get fakemesh.default.role)"

[ "$enabled" = "1" ] && [ "$role" != "controller" ] && interface=meshx0

[ "$INTERFACE" = "$interface" ] || exit 0

[ "$interface" = "meshx0" ] && uci get umdns.@umdns[0] && {
	old_net=$(uci get umdns.@umdns[0].network)
	new_net=$(for net in $old_net meshx0; do echo $net; done | sort | uniq)
	new_net=$(echo $new_net)
#FIXME: since umdns bug, this just an workaroud only
	new_net="meshx0"

	[ "$old_net" != "$new_net" ] && {
		uci delete umdns.@umdns[0].network >/dev/null 2>&1
		for net in $new_net; do
			uci add_list umdns.@umdns[0].network="$net"
		done
		uci commit umdns
		/etc/init.d/umdns reload
	}
}
[ "$interface" = "lan" ] && uci get umdns.@umdns[0] && {
	old_net=$(uci get umdns.@umdns[0].network)
	new_net=$(for net in $old_net lan; do [ "$net" = "meshx0" ] || echo $net; done | sort | uniq)
	new_net=$(echo $new_net)
	[ "$old_net" != "$new_net" ] && {
		uci delete umdns.@umdns[0].network >/dev/null 2>&1
		for net in $new_net; do
			uci add_list umdns.@umdns[0].network="$net"
		done
		uci commit umdns
		/etc/init.d/umdns reload
	}
}

status="$(ubus -S call network.interface.$INTERFACE status)"
[ -n "$status" ] && {
	. /usr/share/libubox/jshn.sh
	json_load "$status"
	json_select "ipv4-address" && {
		json_select 1 && {
			json_get_var address address
			json_get_var mask mask
			test -n "$address" && test -n "$mask" && {
				broadcast="$(ipcalc.sh "$address/$mask" | grep BROADCAST | cut -d= -f2)"
				uci get dawn.@network[0] && {
					old_broadcast="$(uci get dawn.@network[0].broadcast_ip)"
					[ "$broadcast" = "$old_broadcast" ] || {
						uci set dawn.@network[0].broadcast_ip="$broadcast"
						uci commit dawn
						/etc/init.d/dawn reload
					}
				}
			}
		}
	}
}
