#!/bin/sh /etc/rc.common
START=50

run_reboot()
{
	local enable minute hour week
	config_get_bool enable $1 enable

	if [ $enable = 1 ]; then
		config_get week $1 week
		config_get minute $1 minute
		config_get hour $1 hour
		if [ "$minute" = "0" ]; then
			minute="00"
		fi
		if [ $week = 7 ]; then
			week="*"
		fi

		sed -i '/reboot/d' /etc/crontabs/root >/dev/null 2>&1
		echo "$minute $hour * * $week sleep 5 && touch /etc/banner && reboot" >> /etc/crontabs/root
		/etc/init.d/cron restart
		echo "Auto REBOOT has started."
	else
		sed -i '/sleep 5 && touch \/etc\/banner && reboot/d' /etc/crontabs/root >/dev/null 2>&1
		/etc/init.d/cron restart
		echo "Auto REBOOT has canceled."
	fi
}

start()
{
	config_load autoreboot
	config_foreach run_reboot main
}

stop()
{
	echo "Auto REBOOT has stoped."
}
