#!/bin/sh

logger -t fakemesh "dhcp ACTION=$ACTION, MACADDR=$MACADDR, IPADDR=$IPADDR, HOSTNAME=$HOSTNAME"

[ -z "${HOSTNAME##MESH-AGENT_*}" ] || exit 0

case "$ACTION" in
	add | update)
		if grep -q ".* ${HOSTNAME##MESH-AGENT_}.ap.fakemesh" /tmp/hosts/fakemesh; then
			sed -i "s/.* ${HOSTNAME##MESH-AGENT_}.ap.fakemesh/$IPADDR ${HOSTNAME##MESH-AGENT_}.ap.fakemesh/" /tmp/hosts/fakemesh
		else
			echo $IPADDR ${HOSTNAME##MESH-AGENT_}.ap.fakemesh >>/tmp/hosts/fakemesh
		fi
		logger -t fakemesh "dhcp add host: $IPADDR ${HOSTNAME##MESH-AGENT_}.ap.fakemesh"
	;;
	remove)
		sed -i "/.* ${HOSTNAME##MESH-AGENT_}.ap.fakemesh/d" /tmp/hosts/fakemesh
		logger -t fakemesh "dhcp remove host: $IPADDR ${HOSTNAME##MESH-AGENT_}.ap.fakemesh"
	;;
esac

[ "$(cat /tmp/hosts/fakemesh.idx | wc -l)" != "$(cat /tmp/hosts/fakemesh | wc -l)" ] && {
	echo -n >/tmp/hosts/fakemesh.idx
	idx=1
	cat /tmp/hosts/fakemesh | while read ip h; do
		echo $ip $((idx++)).ap.fakemesh >>/tmp/hosts/fakemesh.idx
	done
	/etc/init.d/dnsmasq reload &
}
