#!/bin/sh /etc/rc.common
# Copyright (C) 2015 OpenWrt.org

START=80

USE_PROCD=1

start_service() {
	local CONF=/tmp/nginx.conf
	test -e $CONF || return 0
	[ -d /var/log/nginx ] || mkdir -p /var/log/nginx
	[ -d /var/lib/nginx ] || mkdir -p /var/lib/nginx

	procd_open_instance
	procd_set_param command /usr/sbin/nginx -c $CONF -g 'daemon off;'
	procd_set_param file $CONF
	procd_set_param respawn
	procd_close_instance
}
