#!/bin/sh

[ "$ACTION" = ifup -o "$ACTION" = ifupdate ] || exit 0
[ "$ACTION" = ifupdate -a -z "$IFUPDATE_ADDRESSES" -a -z "$IFUPDATE_DATA" ] && exit 0

logger -t cone_nat "Reloading natcap_wan_ip due to $ACTION of $INTERFACE ($DEVICE)"

/usr/sbin/natcapd natcap_wan_ip

