#!/bin/sh

. /lib/functions.sh
. /lib/functions/network.sh
. /lib/mwan3/common.sh
. /lib/mwan3/mwan3.sh

INTERFACE=""
DEVICE=""
PING="/bin/ping"

IFDOWN_EVENT=0

clean_up() {
	LOG notice "Stopping mwan3track for interface \"${INTERFACE}\""
	exit 0
}

if_down() {
	LOG info "Detect ifdown event on interface ${INTERFACE} (${DEVICE})"
	IFDOWN_EVENT=1
}

validate_track_method() {
	local family method
	method="$1"
	family="$2"
	case "$method" in
		ping)
			if [ "$family" = "ipv4" ]; then
				/usr/bin/ping -4 -W1 -c1 -q 127.0.0.1 >/dev/null 2>&1 && PING="/usr/bin/ping -4" && return 0
				test -x /usr/bin/ping && PING="/usr/bin/ping" && return 0
				test -x /bin/ping && PING="/bin/ping -4" && return 0
			else
				/usr/bin/ping -6 -W1 -c1 -q ::1 >/dev/null 2>&1 && PING="/usr/bin/ping -6" && return 0
				test -x /usr/bin/ping6 && PING="/usr/bin/ping6" && return 0
				test -x /bin/ping && PING="/bin/ping -6" && return 0
			fi
			LOG warn "Missing ping. Please enable BUSYBOX_DEFAULT_PING and recompile busybox or install iputils-ping package."
			return 1
			;;
		arping)
			command -v arping 1>/dev/null 2>&1 || {
				LOG warn "Missing arping. Please install iputils-arping package."
				return 1
			}
			;;
		httping)
			command -v httping 1>/dev/null 2>&1 || {
				LOG warn "Missing httping. Please install httping package."
				return 1
			}
			;;
		nping-*)
			command -v nping 1>/dev/null 2>&1 || {
				LOG warn "Missing nping. Please install nping package."
				return 1
			}
			;;
		*)
			LOG warn "Unsupported tracking method: $track_method"
			return 2
			;;
	esac
}

disconnected() {
	echo "offline" > $MWAN3TRACK_STATUS_DIR/$INTERFACE.$FAMILY/STATUS
	get_uptime > $MWAN3TRACK_STATUS_DIR/$INTERFACE.$FAMILY/OFFLINE
	echo "0" > $MWAN3TRACK_STATUS_DIR/$INTERFACE.$FAMILY/ONLINE
	score=0
	[ "$1" = 1 ] && return
	LOG notice "Interface $INTERFACE($FAMILY) ($DEVICE) is offline"
	env -i ACTION="disconnected" INTERFACE="$INTERFACE" DEVICE="$DEVICE" FAMILY="$FAMILY" /sbin/hotplug-call iface
}

connected() {
	echo "online" > $MWAN3TRACK_STATUS_DIR/$INTERFACE.$FAMILY/STATUS
	echo "0" > $MWAN3TRACK_STATUS_DIR/$INTERFACE.$FAMILY/OFFLINE
	get_uptime > $MWAN3TRACK_STATUS_DIR/$INTERFACE.$FAMILY/ONLINE
	host_up_count=0
	lost=0
	turn=0
	loss=0
	[ "$1" = 1 ] && return
	LOG notice "Interface $INTERFACE($FAMILY) ($DEVICE) is online"
	env -i ACTION="connected" INTERFACE="$INTERFACE" DEVICE="$DEVICE" FAMILY="$FAMILY" /sbin/hotplug-call iface
}

disconnecting() {
	echo "disconnecting" > $MWAN3TRACK_STATUS_DIR/$INTERFACE.$FAMILY/STATUS
	LOG notice "Interface $INTERFACE($FAMILY) ($DEVICE) is disconnecting"
}

connecting() {
	echo "connecting" > $MWAN3TRACK_STATUS_DIR/$INTERFACE.$FAMILY/STATUS
	LOG notice "Interface $INTERFACE($FAMILY) ($DEVICE) is connecting"
}

firstconnect() {
	if [ "$STATUS" = "offline" ]; then
		disconnected 1
	else
		connected 1
	fi
}

update_status() {
	local track_ip=$1

	echo "$1" > $MWAN3TRACK_STATUS_DIR/$INTERFACE.$FAMILY/TRACK_${track_ip}
	[ -z "$3" ] && return
	echo "$3" > $MWAN3TRACK_STATUS_DIR/$INTERFACE.$FAMILY/LATENCY_${track_ip}
	echo "$4" > $MWAN3TRACK_STATUS_DIR/$INTERFACE.$FAMILY/LOSS_${track_ip}
}

main() {
	local reliability count timeout interval failure_interval
	local recovery_interval down up size
	local keep_failure_interval check_quality failure_latency
	local recovery_latency failure_loss recovery_loss
	local max_ttl httping_ssl

	[ -z "$5" ] && echo "Error: should not be started manually" && exit 0

	family=$1
	INTERFACE=$2
	DEVICE=$3
	STATUS=$4
	FAMILY=$family
	mkdir -p $MWAN3TRACK_STATUS_DIR/$INTERFACE.$family
	trap clean_up TERM
	trap if_down USR1

	config_load mwan3
	mwan3_init
	config_get track_method $INTERFACE track_method ping
	config_get_bool httping_ssl $INTERFACE httping_ssl 0
	config_get reliability $INTERFACE reliability 1
	config_get count $INTERFACE count 1
	config_get timeout $INTERFACE timeout 4
	config_get interval $INTERFACE interval 10
	config_get down $INTERFACE down 5
	config_get up $INTERFACE up 5
	config_get size $INTERFACE size 56
	config_get max_ttl $INTERFACE max_ttl 60
	config_get failure_interval $INTERFACE failure_interval $interval
	config_get_bool keep_failure_interval $INTERFACE keep_failure_interval 0
	config_get recovery_interval $INTERFACE recovery_interval $interval
	config_get_bool check_quality $INTERFACE check_quality 0
	config_get failure_latency $INTERFACE failure_latency 1000
	config_get recovery_latency $INTERFACE recovery_latency 500
	config_get failure_loss $INTERFACE failure_loss 40
	config_get recovery_loss $INTERFACE recovery_loss 10

	local score=$((down+up))
	local track_ips=$(echo $* | cut -d ' ' -f 5-99)
	local host_up_count=0
	local lost=0
	local turn=0
	local sleep_time result ping_result ping_result_raw ping_status loss latency
	local SRC_IP

	if [ "$family" = "ipv6" ]; then
		mwan3_get_src_ip6 SRC_IP "$INTERFACE"
	else
		mwan3_get_src_ip SRC_IP "$INTERFACE"
	fi
	validate_track_method "$track_method" "$family" || {
		LOG err "track method($track_method) src_ip($SRC_IP) invalid"
		exit 1
	}

	WRAP() {
		# shellcheck disable=SC2048
		DEVICE=$DEVICE SRCIP=$SRC_IP FWMARK=$MMX_MASK LD_PRELOAD=/lib/mwan3/libwrap_mwan3_sockopt.so.1.0 $*
	}

	firstconnect
	while true; do

		sleep_time=$interval

		for track_ip in $track_ips; do
			if [ x$track_ip = xgateway ]; then
				if [ "$family" = "ipv4" ]; then
					track_ip=`ip r | grep default | grep " "$DEVICE" " | awk '{print $3}' | grep '[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*'`
					test -n "$track_ip" || track_ip=255.255.255.255
				else
					continue
				fi
			fi
			if [ $host_up_count -lt $reliability ]; then
				case "$track_method" in
					ping)
						if [ $check_quality -eq 0 ]; then
							WRAP $PING -n -c $count -W $timeout -s $size -t $max_ttl -q $track_ip &> /dev/null
							result=$?
						else
							ping_result_raw="$(WRAP $PING -n -c $count -W $timeout -s $size -t $max_ttl -q $track_ip 2>/dev/null)"
							ping_status=$?
							ping_result=$(echo "$ping_result_raw" | tail -n2)
							loss="$(echo "$ping_result" | sed -ne 's/.*[^0-9]\([0-9]\+\)% packet loss.*/\1/p')"
							if [ "$ping_status" -ne 0 ] || [ "$loss" -eq 100 ]; then
								latency=999999
								loss=100
							else
								latency="$(echo "$ping_result" | sed -ne 's%\(rtt\|round-trip\).* = [^/]*/\([0-9]\+\).*%\2%p')"
							fi
						fi
					;;
					arping)
						WRAP arping -I $DEVICE -c $count -w $timeout -q $track_ip &> /dev/null
						result=$?
					;;
					httping)
						if [ "$httping_ssl" -eq 1 ]; then
							WRAP httping -c $count -t $timeout -q "https://$track_ip" &> /dev/null
						else
							WRAP httping -c $count -t $timeout -q "http://$track_ip" &> /dev/null
						fi
						result=$?
					;;
					nping-tcp)
						result=$(WRAP nping -c $count $track_ip --tcp | grep Lost | awk '{print $12}')
					;;
					nping-udp)
						result=$(WRAP nping -c $count $track_ip --udp | grep Lost | awk '{print $12}')
					;;
					nping-icmp)
						result=$(WRAP nping -c $count $track_ip --icmp | grep Lost | awk '{print $12}')
					;;
					nping-arp)
						result=$(WRAP nping -c $count $track_ip --arp | grep Lost | awk '{print $12}')
					;;
				esac
				if [ $check_quality -eq 0 ]; then
					if [ $result -eq 0 ]; then
						let host_up_count++
						update_status "$track_ip" "up"

						if [ $score -le $up ]; then
							LOG info "Check ($track_method) success for target \"$track_ip\" on interface $INTERFACE($family) ($DEVICE). Current score: $score"
						fi
					else
						let lost++
						update_status "$track_ip" "down"

						if [ $score -gt $up ]; then
							LOG info "Check ($track_method) failed for target \"$track_ip\" on interface $INTERFACE($family) ($DEVICE). Current score: $score"
						fi
					fi
				else
					if [ "$loss" -ge "$failure_loss" ] || [ "$latency" -ge "$failure_latency" ]; then
						let lost++
						update_status "$track_ip" "down" $latency $loss

						if [ $score -gt $up ]; then
							LOG info "Check (${track_method}: latency=${latency}ms loss=${loss}%) failed for target \"$track_ip\" on interface $INTERFACE($family) ($DEVICE). Current score: $score"
						fi
					elif [ "$loss" -le "$recovery_loss" ] && [ "$latency" -le "$recovery_latency" ]; then
						let host_up_count++
						update_status "$track_ip" "up" $latency $loss

						if [ $score -le $up ]; then
							LOG info "Check (${track_method}: latency=${latency}ms loss=${loss}%) success for target \"$track_ip\" on interface $INTERFACE($family) ($DEVICE). Current score: $score"
						fi
					else
						echo "skipped" > $MWAN3TRACK_STATUS_DIR/$INTERFACE.$family/TRACK_${track_ip}
					fi
				fi
			else
				echo "skipped" > $MWAN3TRACK_STATUS_DIR/$INTERFACE.$family/TRACK_${track_ip}
			fi
		done

		if [ $host_up_count -lt $reliability ]; then
			let score--

			if [ $score -lt $up ]; then
				score=0
				[ ${keep_failure_interval} -eq 1 ] && {
					sleep_time=$failure_interval
				}
			else
				disconnecting
				sleep_time=$failure_interval
			fi

			if [ $score -eq $up ]; then
				disconnected
				score=0
			fi
		else
			if [ $score -lt $((down+up)) ] && [ $lost -gt 0 ]; then
				connecting
				LOG info "Lost $((lost*count)) ping(s) on interface $INTERFACE($family) ($DEVICE). Current score: $score"
			fi

			let score++
			lost=0

			if [ $score -gt $up ]; then
				echo "online" > $MWAN3TRACK_STATUS_DIR/$INTERFACE.$family/STATUS
				score=$((down+up))
			elif [ $score -le $up ]; then
				connecting
				sleep_time=$recovery_interval
			fi

			if [ $score -eq $up ]; then
				connected
			fi
		fi

		let turn++
		mkdir -p "$MWAN3TRACK_STATUS_DIR/$INTERFACE.$family"
		echo "${lost}" > $MWAN3TRACK_STATUS_DIR/$INTERFACE.$family/LOST
		echo "${score}" > $MWAN3TRACK_STATUS_DIR/$INTERFACE.$family/SCORE
		echo "${turn}" > $MWAN3TRACK_STATUS_DIR/$INTERFACE.$family/TURN
		get_uptime > $MWAN3TRACK_STATUS_DIR/$INTERFACE.$family/TIME

		host_up_count=0
		sleep "${sleep_time}" &
		wait

		if [ "${IFDOWN_EVENT}" -eq 1 ]; then
			LOG debug "Register ifdown event on interface ${INTERFACE}($family) (${DEVICE})"
			disconnected 1
			IFDOWN_EVENT=0
		fi
	done
}

main "$@"
