#!/bin/sh

case "$ACTION" in
	add)
		case "$INTERFACE" in
			br-lanap|br-lanrelay|br-lan)
				ip addr del 169.254.254.254/16 dev $INTERFACE
				ifconfig $INTERFACE:1 169.254.254.254 netmask 255.255.0.0
			;;
		esac
	;;
	ifup|ifupdate)
		case "$DEVICE" in
			br-lanap|br-lanrelay|br-lan)
				ip addr del 169.254.254.254/16 dev $DEVICE
				ifconfig $DEVICE:1 169.254.254.254 netmask 255.255.0.0
			;;
		esac
	;;
esac

exit 0
