#!/bin/sh /etc/rc.common

START=99

boot() {
	XBOOT=1 start
}

start() {
	band_steer_helper=$(uci get fakemesh.default.band_steer_helper || echo usteer) exec /usr/sbin/fakemesh band_steer_helper_switch
	/usr/sbin/fakemesh
}

restart() {
	XRELOAD=1 start
}
